alias b := backend
alias f := frontend

[working-directory('src/backend')]
backend:
    python main.py && rm -r __pycache__

[working-directory('src/frontend')]
frontend:
    python main.py && rm -r controller/__pycache__ && rm -r model/__pycache__ && rm -r view/__pycache__
